#!/bin/bash
train()
{
	google-chrome --new-window "https://docs.google.com/spreadsheets/d/1UvipUZ4DrR6NYZfKazqZwo_GXvNzJacMWW0fHgnCJMM/edit?usp=sharing"  "https://www.sololearn.com/Play/java" &
	lyx /home/atai/Google\ Drive/FRC/EverGreen\ \#7112/FRC\ 2019-20/צוותים/תוכנה/הכשרות/תוכנית\ הכשרות-2.lyx &
	code -r ~/Documents/Test/Hello &
}


lib()
{
	code /home/atai/Documents/GitHub/EverLib &
	code /home/atai/Documents/GitHub/Everlib-Test &
	google-chrome --new-window https://github.com/wpilibsuite/allwpilib/tree/master/wpilibj/src/main/java/edu/wpi/first/wpilibj https://github.com/EverGreen7112/DeepSpace2019/blob/master/DeepSpace7112/src/main/java/frc/robot  https://github.com/EverGreen7112/DeepSpace2019/blob/master/DeepSpace7112/src/main/java/frc/robot/PortMaps/ButtonMap.java
}

app()
{
	cd /home/atai/Documents/GitHub/EverApp &&

	if [ "$1" == "push" ]; then
		git push
	else
		/opt/android-studio-preview/bin/studio.sh . 
	fi
}


list()
{
	printf "train - Software Robotics Training\nlib - Everlib\napp - EverApp\n" 
}
eval "$1 $2"
