#!/bin/bash

math()
{
	EXERCISE_PATH="~/gdrive/Studies/School/Exercise/Math"
	echo "$1"
	
		#Get sub-folder (SUBJECT), textbook url and file name (which is the date of the next lesson).
	echo "determining subject"
	
	case $1 in
	"calc")
		SUBJECT="Calculus"
		BOOK="https://my.classoos.com/viewbook/1504"
		DATE=$(date -dnext-thursday  +”%d.%m.%Y”)
		;;
	
	"series")
		SUBJECT="Series"
		BOOK="https://my.classoos.com/viewbook/1498"

		#Series is on both sunday and wednesday. Check which is closer and put in DATE.
		SUN=$(date -dnext-sunday +%Y%m%d) 
		WED=$(date -dnext-wednesday +%Y%m%d)
		if [ "$SUN" -ge "$WED" ]; then
			DATE=$(date -dnext-sunday +%d.%m.%y)
		else
			DATE=$(date -dnext-wednesday +%d.%m.%y)
		fi
		;;
	
	"trig")
		SUBJECT="Trigonometry"
		BOOK="https://my.classoos.com/viewbook/1498"
		DATE=$(date -dnext-monday  +%d.%m.%Y)
		;;
	
	
	"test")
		Subject="Tests"
		BOOK="https://my.classoos.com/viewbook/1498 https://my.classoos.com/viewbook/1504"
		
		if [ -n "$2" ]; then
			DATE="Test - $(eval "date -dnext-$2 +%d.%m.%y ")"
		else
			DATE="Test "
		fi
		;;


	"macros")
		lyx -r "$EXERCISE_PATH/Macros.lyx"
		shift
		;;
	*)
		echo "error: no subject specified"
		;;
	esac


	if [ -n "$1" ]; then
		google-chrome --new-window "https://www.desmos.com/calculator" "learntube.co.il/formula/5.pdf" "https://www.symbolab.com/" "https://www.youtube.com/playlist?list=PLofIPNHWuL8-XfMbL3-atHEyidoc4qi6j" "$BOOK"
		FILE_PATH="$EXERCISE_PATH/$SUBJECT/$DATE.lyx"
		echo "File: $FILE_PATH"
		if [ ! -f "$FILE_PATH" ]; then
			lyx -r "$EXERCISE_PATH/Macros.lyx" &
		fi
	
		lyx -r "$FILE_PATH" &

	fi
}

#phys()
#{
	#SUN=$(date -dnext-sunday +%Y%m%d)
	#WED=$(date -dnext-wednesday +%Y%m%d)
	#THU=$(date -dnext-wednesday +%Y%m%d)
	#if [$SUN -ge $WED]; then
#		DATE=$(date -denext-wednesday +%d.%m.%y)
	#else
	#	if [
#}


cs()
{
	google-chrome --new-window https://my.classoos.com/viewbook/8599 &
	code &
}

case $1 in
"-t")
	eval "$3 test $2";;
*) 
	eval "$1 $2";;
esac
