#!/bin/bash

math()
{
	FOLDER_PATH="~/gdrive/Studies/School/Exercise/Math"
	echo "$1"
	
		#Get sub-folder (SUBJECT), textbook url and file name (which is the date of the next lesson).
	echo "determining subject"
	while [ -n $1 ]; do
		case $1 in
		"calc")
			SUBJECT="Calculus"
			BOOK="https://my.classoos.com/viewbook/1504"
			DATE=$(date -dnext-monday  +”%d.%m.%Y”)
			shift
			;;
		
		"seq")
			SUBJECT="Sequences"
			BOOK="https://my.classoos.com/viewbook/1498"

			#Series is on both sunday and wednesday. Check which is closer and put in DATE.
			SUN=$(date -dnext-sunday +%Y%m%d) 
			WED=$(date -dnext-wednesday +%Y%m%d)
			if [ "$SUN" -ge "$WED" ]; then
				DATE=$(date -dnext-sunday +%d.%m.%y)
			else
				DATE=$(date -dnext-wednesday +%d.%m.%y)
			fi
			shift
			;;
		
		"trig")
			SUBJECT="Trigonometry"
			BOOK="https://my.classoos.com/viewbook/1498"
			DATE=$(date -dnext-thursday  +%d.%m.%Y)
			shift
			;;

		"macros")
			lyx -r "$FOLDER_PATH/Macros.lyx"
			shift
			;;
		
		"lesson")
			EXTRA="Lesson - "
			FOLDER_PATH="/home/atai/gdrive/Studies/School/Lessons/Math"
			shift
			;;
		"-s")
			EXTRA=$2
			FOLDER_PATH="/home/atai/gdrive/Studies/School/Summary-Editor/Math"
			DATE=""
			shift
			shift
			;;
		"test")
			Subject="Tests"
			BOOK="https://my.classoos.com/viewbook/1498 https://my.classoos.com/viewbook/1504"
			
			if [ -n "$2" ]; then
				EXTRA="Test - "
				DATE=$(date -dnext-$2 +%d.%m.%y)
			else
				EXTRA="Test"
			fi

			shift
			shift
			;;
		*)
			echo "$1"
			shift
			break
			;;
		esac
	done


	#if [ -n "$0" ]; then
		google-chrome --new-window "https://www.desmos.com/calculator" "learntube.co.il/formula/5.pdf" "https://www.symbolab.com/" "https://music.youtube.com/playlist?list=PLofIPNHWuL8-XfMbL3-atHEyidoc4qi6j" "https://www.mathpapa.com/algebra-calculator.html" "$BOOK"
		FILE_PATH="$FOLDER_PATH/$SUBJECT/$EXTRA$DATE.lyx"
		echo "File: $FILE_PATH"
	#	if [ ! -f "$FILE_PATH" ]; then
			lyx -r "$FOLDER_PATH/Macros.lyx" &
		#fi
	
		lyx -r "$FILE_PATH" &

	#fi
}

#phys()
#{
#	SUN=$(date -dnext-sunday +%Y%m%d)
#	WED=$(date -dnext-wednesday +%Y%m%d)
#	THU=$(date -dnext-wednesday +%Y%m%d)
#	if [$SUN -ge $WED]; then
#		DATE=$(date -denext-wednesday +%d.%m.%y)
#	else
#		if [
#}


cs()
{
	google-chrome --new-window https://my.classoos.com/viewbook/8599 &
	code &
}

case $1 in
"-t")
	eval "$2 test $3";;
"-l")
	eval "$2 $3 lesson";;
"--help")
	echo "test";;
*) 
	eval "$1 $2";;
esac
