#!/bin/bash

math()
{
	while getopts ":ls:" opt; do
		case ${opt} in
		l)
			DATE=$(date +%d.%m.%y) #Date for file name
			TODAY=$(date +%a) 
			case $TODAY in 
				Sun|Wed)
					SUBJECT="Sequence";;
				Mon)
					SUBJECT="Trigonometry";;
				Thu)
					SUBJECT="Calculus";;
				*)
					if [ -n $2]; then EXTENSION=$(echo $2| cut -c3-${#2}); #If specific 
					else EXTENSION="lyx"
						xdg-open $(find "$FOLDER_PATH" -type f -name "* Lesson - *.$EXTENSION" -printf '%T@ %p\n' | sort -n |tail -1 | cut -f2- -d" ")
					fi
				

					exit [0]
				esac
			
			FILE_NAME="$SUBJECT Lesson - $DATE.$EXTENSION" 
			
				
			echo "Name - $FILE_NAME"
			shift
		;;
		

		
}

# phys()
#{
	#SUN=$(date -dnext-sunday +%Y%m%d)
	#WED=$(date -dnext-wednesday +%Y%m%d)
	#THU=$(date -dnext-wednesday +%Y%m%d)
	#if [$SUN -ge $WED]; then
#		DATE=$(date -denext-wednesday +%d.%m.%y)
	#else
	#	if [
#}


recurs()
{
	google-chrome --new-window https://my.classoos.com/viewbook/8599 &
	code ~/Documents/GitHub/School-Exercises/Recursion &
}

case $1 in
"-t")
	eval "$3 test $2";;
*) 
	eval "$1 $2";;
esac
