#!/bin/bash

math()
{
	FOLDER_PATH="~/gdrive/Studies/School/Exercise/Math" #Set up exercise directory.
	EXERCISE=true
	NEW=false


	while [ -n "$1" ]; do	
		case $1 in 
		"-l")
			DATE=$(date +%d.%m.%y) #Date for file name
			TODAY=$(date +%a) 
			case $TODAY in 
			Sun|Wed)
				SUBJECT="Sequence";;
			Mon)
				SUBJECT="Trigonometry";;
			Thu)
				SUBJECT="Calculus";;
			*)
				if [ -n $2]; then EXTENSION=$(echo $2| cut -c3-${#2}); #If specific 
				else EXTENSION="lyx"
					xdg-open $(find "$FOLDER_PATH" -type f -name "* Lesson - *.$EXTENSION" -printf '%T@ %p\n' | sort -n |tail -1 | cut -f2- -d" ")
				fi
				

				exit [0];;
			esac
			
		FILE_NAME="$SUBJECT Lesson - $DATE.$EXTENSION" 
		
			
		echo "Name - $FILE_NAME";;
		shift
		
		"-s")
			FOLDER_PATH="~/gdrive/Studies/School/Summaries/Math"
			EXTENSION="pdf"
			NEW=false #default file type for summaries.
		"--lyx")
			EXTENSION="lyx"
		"--pdf")
			EXTENSION="pdf"	
	
		esac
	done

	xdg-open "$FOLDER_PATH/$NAME"
	
	if [ "$1" == "--lyx" ] #Check for forced 
		EXTENSION="lyx"
		EXERCISE_PATH="~/gdrive/Studies/School/Summaries/Math"
	
	elif [ "$1" == "--pdf"]
		EXTENSION="pdf"
	fi
	
		#Get sub-folder (SUBJECT), textbook url and file name (which is the date of the next lesson).
	echo "determining subject"

	if [ "$1" == "calc" ]; then
		SUBJECT="Calculus"
		BOOK="https://my.classoos.com/viewbook/1504"
		DATE=$(date -dnext-thursday  +”%d.%m.%Y”)
	
	elif [ "$1" == "seq" ]; then
		SUBJECT="Sequences"
		BOOK="https://my.classoos.com/viewbook/1498"

		#Series is on both sunday and wednesday. Check which is closer and put in DATE.
		SUN=$(date -dnext-sunday +%Y%m%d) 
		WED=$(date -dnext-wednesday +%Y%m%d)
		if [ "$SUN" -ge "$WED" ]; then
			DATE=$(date -dnext-sunday +%d.%m.%y)
		else
			DATE=$(date -dnext-wednesday +%d.%m.%y)
		fi
	
	elif [ "$1" == "trig" ]; then
		SUBJECT="Trigonometry"
		BOOK="https://my.classoos.com/viewbook/1498"
		DATE=$(date -dnext-monday  +%d.%m.%Y)
	
	
	elif [ "$1" == "test" ]; then
		Subject="Tests"
		BOOK="https://my.classoos.com/viewbook/1498 https://my.classoos.com/viewbook/1504"
		
		if [ -n "$2" ]; then
			DATE="Test - $(eval "date -dnext-$2 +%d.%m.%y")"
		else
			DATE="Test "
		fi


	elif [ "$1" == "macros" ]; then
		lyx "$EXERCISE_PATH/Macros.lyx"
		shift
	else
		echo "error: no subject specified"
	fi


	if [ -n "$1" ]; then
		google-chrome --new-window "https://www.desmos.com/calculator" "learntube.co.il/formula/5.pdf" "https://www.symbolab.com/" "https://www.youtube.com/playlist?list=PLofIPNHWuL8-XfMbL3-atHEyidoc4qi6j" "$BOOK"
		FILE_PATH="$EXERCISE_PATH/$SUBJECT/$DATE.lyx"
		echo "File: $FILE_PATH"
		if [ ! -f "$FILE_PATH" ]; then
			lyx "$EXERCISE_PATH/Macros.lyx" &
		fi
	
		lyx "$FILE_PATH" &

	fi
}

#phys()
#{
	#SUN=$(date -dnext-sunday +%Y%m%d)
	#WED=$(date -dnext-wednesday +%Y%m%d)
	#THU=$(date -dnext-wednesday +%Y%m%d)
	#if [$SUN -ge $WED]; then
#		DATE=$(date -denext-wednesday +%d.%m.%y)
	#else
	#	if [
#}


recurs()
{
	google-chrome --new-window https://my.classoos.com/viewbook/8599 &
	code ~/Documents/GitHub/School-Exercises/Recursion &
}

case $1 in
"-t")
	eval "$3 test $2";;
*) 
	eval "$1 $2";;
esac
