#!/bin/bash

stone() 
{
	cd ~/Videos/Series/Doctor\ Stone
	
	echo "$1"
	
	if  [[ $1 =~ "^\[0-9]+$" ]]; then
		echo $(find . -name "Episode $1 - *.mkv")
		vlc $(find . -name "Episode $1 - *.mkv")
	else
		case "$1" in
		"-c")
			NUM=$(cat .EpKeeper)
			echo $NUM
			echo $(find . -name "Episode $NUM - *.mkv")
			vlc $(find . -name "Episode $NUM - *.mkv")
			;;
		"-o") 
			LAST_FILE_OPENED=$(ls . -u -t | head -1)
			echo $LAST_FILE_OPENED
			[[ $FOUND =~ Episode[[:space:]]([0-9]*)[[:space:]]- ]]
			LAST_NUM=${BASE_REMATCH[1]}
			echo $LAST_NUM
			EP_NUM=$((LAST_NUM + 1))
			echo $EP_NUM
			echo $(find . -name "Episode $EP_NUM - *.mkv")
			vlc $(find . -name "Episode $EP_NUM - *.mkv")
			;;
		*)
			LAST=$(cat .EpKeeper)	
			EP_NUM=$((LAST + 1))
			echo $EP_NUM			
			echo $EP_NUM > .EpKeeper
			echo $(cat .EpKeeper)
			echo $(find . -name "Episode $EP_NUM - *.mkv")
						
			vlc $(find . -name "Episode $EP_NUM - *.mkv" | cut -b3-$(expr length )
)
			;;
		esac
	fi
}

$1 $2
