#!/bin/bash
if [ -f ~/.bin/$1 ]; then
	echo "Script already exist!"
	exit 2
else
	script_path="~/.bin/$1"
	echo $script_path
	printf "#!/bin/bash\n" > "$script_path"
	emacs "$sctipt_path"
	chmod +x "$script_path"
fi
