#!/bin/env bash

case "$1" in
    rprt)
        report="$REPORT/$(date +%m\ %B)/$(date +%d,\ %A).lyx"
        lyx -e pdf "$report"
        ;;
    songs)
        cd $MEDIA/Music
        new_songs="https://www.youtube.com/playlist?list=PLofIPNHWuL887M4D2FSUN1BbxII4DBsN4"
        youtube-dl -x --audio-format mp3 "$new_songs"
        ;;
    laws)
        find "$(readlink -f ~/Projects/LAWBOOK.prj)" -type f  -name "*.lyx" -exec lyx -e pdf {} \;
        ;;
    *)

esac
